# 기본 환경설정
spring:
  profiles:
    active: development
    include: config

server:
  servlet:
    context-path: /timeline

# 개발환경
---
spring:
  profiles: development

logging:
  config: classpath:api-dev-logback.xml

# 운영환경 설정
---
spring:
  profiles: production

server:
  port: 8081


logging:
  config: classpath:api-prob-logback.xml