# 기본 환경설정
spring:
  profiles:
    active: development
    include: config

# 개발환경
---
spring:
  profiles: development

logging:
  config: classpath:batch-dev-logback.xml

# 운영환경 설정
---
spring:
  profiles: production

server:
  port: 8082

logging:
  config: classpath:batch-prob-logback.xml