# 기본 환경설정
spring:
  profiles:
    active: development
    include: spring

# 개발환경
---
spring:
  profiles: development
  batch:
    job:
      names: timelineCrawlerJob
      enabled: false
#    initialize-schema: always

# 운영환경 설정
---
spring:
  profiles: production
  batch:
    job:
      names: timelineCrawlerJob
      enabled: false

