spring:
  profiles:
    active: development


# develop
---
spring:
  profiles: development

config:
  kafka-topic:
    item: wedul_timeline

redis:
  host: 127.0.0.1
  port: 6379

server:
  port: 8081

# 운영환경 설정
---

spring:
  profiles: production

config:
  kafka-topic:
    item: wedul_timeline

redis:
  host: 192.168.219.120
  port: 36379