spring:
  profiles:
    active: development

# develop
---
spring:
  profiles: development
  mvc:
    throw-exception-if-no-handler-found: true

# 운영환경 설정
---
spring:
  profiles: production
  mvc:
    throw-exception-if-no-handler-found: true