spring:
  profiles:
    active: development


# develop
---
spring:
  profiles: development

  flyway:
    enabled: true
    baselineOnMigrate: true
    encoding: UTF-8

config:
  kafka-topic:
    item: wedul_timeline

redis:
  host: 192.168.219.120
  port: 36379

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.apache.kafka: WARN
    com.wedul.wedul_timeline: DEBUG
    java.sql: DEBUG
    java.sql.ResultSet: DEBUG
    com.zaxxer.hikari: ERROR
  file: ./logs/batch.%d{yyyy-MM-dd}.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

server:
  port: 8081

# 운영환경 설정
---

spring:
  profiles: production

  flyway:
    enabled: true
    baselineOnMigrate: true
    encoding: UTF-8

config:
  kafka-topic:
    item: wedul_timeline

redis:
  host: 192.168.219.120
  port: 36379