spring:
  profiles:
    active: development


# develop
---
spring:
  profiles: development

  datasource:
    username: /88M772kGsUdE/yutXxF2A==

    dbcp2:
      validation-query: SELECT 1

    password: BMvZUaivNfJmCxyGy29ykw==

    tomcat:
      connection-properties: useUnicode=yes&characterEncoding=utf8;useSSL=false

    url: jdbc:mysql://192.168.219.120:3307/wedul?useUnicode=yes&characterEncoding=utf8&autoReconnect=true
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  session:
    store-type: redis

  kafka:
    bootstrap-servers:
      127.0.0.1:9092
    consumer:
      group-id: wedul_timeline_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    template:
      default-topic: wedul_timeline
# 운영환경 설정
---
spring:
  profiles: production

  datasource:
    username: /88M772kGsUdE/yutXxF2A==

    dbcp2:
      validation-query: SELECT 1

    password: BMvZUaivNfJmCxyGy29ykw==

    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.219.120:3307/wedul?useUnicode=yes&characterEncoding=UTF8&autoReconnect=true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  session:
    store-type: redis

  kafka:
    bootstrap-servers:
      127.0.0.1:9092
    consumer:
      group-id: wedul_timeline_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    template:
      default-topic: wedul_timeline