spring:
  profiles:
    active: development


# develop
---
spring:
  profiles: development
  datasource:
    username: /88M772kGsUdE/yutXxF2A==

    dbcp2:
      validation-query: SELECT 1

    password: BMvZUaivNfJmCxyGy29ykw==

    tomcat:
      connection-properties: useUnicode=yes&characterEncoding=utf8;useSSL=false

    url: jdbc:mysql://192.168.219.120:3307/wedulpos?useUnicode=yes&characterEncoding=utf8&autoReconnect=true
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: 127.0.0.1
    port: 6379

  session:
    store-type: redis

# 운영환경 설정
---
spring:
  profiles: production

  datasource:
    username: /88M772kGsUdE/yutXxF2A==

    dbcp2:
      validation-query: SELECT 1

    password: BMvZUaivNfJmCxyGy29ykw==

    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/wedulpos?useUnicode=yes&characterEncoding=UTF8&autoReconnect=true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: 127.0.0.1
    port: 36379


  session:
    store-type: redis