logging:
  level:
    root: WARN
    org.springframework: WARN
    org.apache.kafka: WARN
    com.wedul.wedul_timeline: WARN
    java.sql: INFO
    java.sql.ResultSet: INFO
    com.zaxxer.hikari: ERROR


spring:
  profiles:
    active: development


# develop
---
config:
  kafka-topic:
    item: wedul_timeline


# 운영환경 설정
---
config:
  kafka-topic:
    item: wedul_timeline